CC=~/djgpp/720/bin/i586-pc-msdosdjgpp-gcc
SRC=./src/a.c
BIN=./bin/a.exe
DEPLOYDIR=/mnt/c/tmp/dosdrive/tmp
CFLAGS=-DNDEBUG
LDFLAGS=
$(BIN): $(SRC)
	@-echo compiling $(@D)
	@-mkdir -p $(@D)
	@-$(CC)\
		$(CFLAGS)\
		$(SRC)\
		$(LDFLAGS)\
		-o $(BIN)
run: $(BIN)
	@-echo executing $(@D)
	@-$(BIN)
.phony:\
	clean\
	deploy
clean:
	@-rm $(BIN)
deploy:$(BIN)
	@-cp\
		$(BIN) \
		$(DEPLOYDIR)
