CC=bcc
SRCDIR=.\src
BINDIR=.\bin
SRC=$(SRCDIR)\a.c
OBJ=$(BINDIR)\a.obj
BIN=$(BINDIR)\a.exe
RM=del
$(BIN): $(OBJ)
	$(CC) $(OBJ)
$(OBJ): $(SRC)
	$(CC) -c -n$(BINDIR) $(SRC)
clean:
	@$(RM) .\bin\*.*
run: $(BIN)
	$(BIN)
